# Generated by Django 5.2.9 on 2026-01-03 11:40

import django.contrib.postgres.fields
import django.db.models.deletion
import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        pgvector.django.VectorExtension(),
        migrations.CreateModel(
            name='FeatureColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('histogram', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), help_text='HSV Histogram Vector', size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='color_feature', to='core.imagemetadata')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureSemantic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=2048, help_text='ResNet50 Embedding')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='semantic_feature', to='core.imagemetadata')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureShape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hog_vector', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), help_text='HOG Vector', size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shape_feature', to='core.imagemetadata')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureTexture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lbp_histogram', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), help_text='LBP Histogram Vector', size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='texture_feature', to='core.imagemetadata')),
            ],
        ),
    ]
