# Generated by Django 5.0 on 2025-12-21 16:20

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, unique=True, verbose_name='File Name')),
                ('relative_path', models.CharField(max_length=500, verbose_name='Relative Path')),
                ('width', models.IntegerField(default=0, verbose_name='Width (px)')),
                ('height', models.IntegerField(default=0, verbose_name='Height (px)')),
                ('format', models.CharField(blank=True, max_length=50, verbose_name='Image Format')),
                ('mode', models.CharField(blank=True, max_length=50, verbose_name='Color Mode')),
                ('labels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None, verbose_name='Labels')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Corel-5K Image',
                'verbose_name_plural': 'Corel-5K Images',
            },
        ),
        migrations.CreateModel(
            name='ImageFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('color_histogram', 'Color Histogram (HSV)'), ('glcm', 'Gray Level Co-occurrence Matrix (GLCM)'), ('sobel', 'Sobel Edge Detection'), ('fused', 'Fused Features')], max_length=50, verbose_name='Feature Extraction Method')),
                ('vector', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None, verbose_name='Feature Vector')),
                ('dimension', models.IntegerField(verbose_name='Feature Dimension')),
                ('extraction_time', models.FloatField(default=0.0, verbose_name='Extraction Time (seconds)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.corelimage')),
            ],
            options={
                'verbose_name': 'Image Feature',
                'verbose_name_plural': 'Image Features',
                'unique_together': {('image', 'method')},
            },
        ),
    ]
